name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      # Käytetään päivitettyä versiota actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Käytetään päivitettyä versiota actions/setup-node ja asetetaan Node.js 22
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Asennetaan projektin riippuvuudet
      - name: Install dependencies
        run: npm install

      # Suoritetaan testit ja luodaan kattavuusraportti
      - name: Run tests with coverage
        run: npm test -- --coverage

      # Lähetetään kattavuusraportti Coveralls-palveluun
      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run coveralls
